<a href="https://colab.research.google.com/github/Yihong-Z/DataTidying/blob/main/Matrix0506.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Read in data

In [1]:
import pandas as pd
import numpy as np

In [2]:
carbon=pd.read_csv("/content/Biochar carbon stock 100 year_1km_pature_lower_yr2.csv")
df=pd.read_csv("/content/Dead tree_pasture_1km_lower.csv")
row=pd.read_csv("/content/Row1.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
row.head()

Carbon stock
0    516.077809
1    213.498891
2    212.999796
3    212.615905
4    212.253905

In [4]:
row_matrix=np.array(row.transpose())

In [5]:
df.head()

pointid     SI  1         2         3         4         5         6  \
0      1.0  100.0  0  0.000808  0.004633  0.022418  0.066473  0.152868   
1      6.0  100.0  0  0.000808  0.004633  0.022418  0.066473  0.152868   
2     12.0   79.0  0  0.000709  0.006546  0.009268  0.040315  0.110476   
3     17.0   98.0  0  0.004866  0.029183  0.140289  0.414871  0.952972   
4     18.0   77.0  0  0.000163  0.001580  0.002226  0.009612  0.026260   

          7         8  ...         91         92         93         94  \
0  0.299574  0.368845  ...   2.273333   2.402403   2.518093   3.295817   
1  0.299574  0.368845  ...   2.273333   2.402403   2.518093   3.295817   
2  0.240183  0.294589  ...   2.217918   2.361950   2.495736   2.618450   
3  1.866733  2.297738  ...  14.214576  15.031839  15.766964  16.416736   
4  0.057013  0.069874  ...   0.527322   0.561928   0.594173   0.623852   

          95         96         97         98         99        100  
0   3.404649   3.495997   3.570239   3.627979   4.506800   4.538685  
1   3.404649   3.495997   3.570239   3.627979   4.506800   4.538685  
2   3.539014   3.665680   3.776629   3.871908   3.951763   4.016610  
3  21.354697  21.944376  22.427703  22.808132  23.090237  28.583556  
4   0.650820   0.875005   0.902228   0.925766   0.945665   0.962010  

[5 rows x 102 columns]

In [6]:
#DROP MULTIPLE COLUMNS: dataframe.drop(columns=['column_name_1', 'column_name_2'])
#df.iloc[:,0:3]
df_base=df.drop(columns=["pointid","SI","1"])

In [7]:
df_base=df_base.drop([11710])

In [12]:
df_base.shape

(11710, 99)

In [13]:
df_base

2         3         4         5         6         7         8  \
0      0.000808  0.004633  0.022418  0.066473  0.152868  0.299574  0.368845   
1      0.000808  0.004633  0.022418  0.066473  0.152868  0.299574  0.368845   
2      0.000709  0.006546  0.009268  0.040315  0.110476  0.240183  0.294589   
3      0.004866  0.029183  0.140289  0.414871  0.952972  1.866733  2.297738   
4      0.000163  0.001580  0.002226  0.009612  0.026260  0.057013  0.069874   
...         ...       ...       ...       ...       ...       ...       ...   
11705  0.000275  0.001973  0.009221  0.026945  0.061565  0.078432  0.147906   
11706  0.000825  0.005920  0.027662  0.080836  0.184694  0.235296  0.443718   
11707  0.001593  0.014255  0.028222  0.115917  0.149314  0.388084  0.472458   
11708  0.000825  0.005920  0.027662  0.080836  0.184694  0.235296  0.443718   
11709  0.000677  0.005445  0.024953  0.034694  0.095855  0.209142  0.257006   

              9        10        11  ...         91         92         93  \
0      0.627373  0.731353  0.835483  ...   2.273333   2.402403   2.518093   
1      0.627373  0.731353  0.835483  ...   2.273333   2.402403   2.518093   
2      0.539374  0.629626  0.721382  ...   2.217918   2.361950   2.495736   
3      3.909069  4.557514  5.207814  ...  14.214576  15.031839  15.766964   
4      0.127910  0.149288  0.171051  ...   0.527322   0.561928   0.594173   
...         ...       ...       ...  ...        ...        ...        ...   
11705  0.176763  0.293638  0.335837  ...   0.715148   0.983945   1.035006   
11706  0.530289  0.880913  1.007511  ...   2.145444   2.951835   3.105019   
11707  0.964395  1.124286  1.975116  ...   4.569937   4.891179   5.196103   
11708  0.530289  0.880913  1.007511  ...   2.145444   2.951835   3.105019   
11709  0.470731  0.549640  0.895347  ...   1.919341   2.039935   2.789362   

              94         95         96         97         98         99  \
0       3.295817   3.404649   3.495997   3.570239   3.627979   4.506800   
1       3.295817   3.404649   3.495997   3.570239   3.627979   4.506800   
2       2.618450   3.539014   3.665680   3.776629   3.871908   3.951763   
3      16.416736  21.354697  21.944376  22.427703  22.808132  23.090237   
4       0.623852   0.650820   0.875005   0.902228   0.925766   0.945665   
...          ...        ...        ...        ...        ...        ...   
11705   1.080862   1.121357   1.156435   1.491815   1.521926   1.545653   
11706   3.242587   3.364071   3.469304   4.475446   4.565777   4.636958   
11707   5.482654   7.751740   8.078475   8.375417   8.641866   8.877541   
11708   3.242587   3.364071   3.469304   4.475446   4.565777   4.636958   
11709   2.918344   3.033507   3.134592   3.221572   3.294625   4.217811   

             100  
0       4.538685  
1       4.538685  
2       4.016610  
3      28.583556  
4       0.962010  
...          ...  
11705   1.563277  
11706   4.689832  
11707   9.082531  
11708   4.689832  
11709   4.274636  

[11710 rows x 99 columns]

In [14]:
df_matrix=np.array(df_base)

In [15]:
df_matrix[:,0]

array([0.00080791, 0.00080791, 0.00070942, ..., 0.00159319, 0.00082476,
       0.00067741])

In [16]:
df_matrix_1=np.matrix(df_base.iloc[:,0]).transpose()

In [17]:
df_matrix_1

matrix([[0.00080791],
        [0.00080791],
        [0.00070942],
        ...,
        [0.00159319],
        [0.00082476],
        [0.00067741]])

In [18]:
row_matrix

array([[516.0778087, 213.4988909, 212.9997964, 212.615905 , 212.2539052,
        211.8964608, 211.5403502, 211.1849739, 210.83022  , 210.4760667,
        210.1225091, 209.7695456, 209.4171751, 209.0653965, 208.7142088,
        208.363611 , 208.0136021, 207.6641812, 207.3153473, 206.9670993,
        206.6194363, 206.2723573, 205.9258614, 205.5799474, 205.2346146,
        204.8898618, 204.5456882, 204.2020927, 203.8590743, 203.5166322,
        203.1747653, 202.8334726, 202.4927533, 202.1526063, 201.8130307,
        201.4740255, 201.1355898, 200.7977225, 200.4604229, 200.1236898,
        199.7875223, 199.4519196, 199.1168806, 198.7824044, 198.44849  ,
        198.1151366, 197.7823431, 197.4501086, 197.1184323, 196.7873131,
        196.4567501, 196.1267423, 195.797289 , 195.468389 , 195.1400415,
        194.8122456, 194.4850003, 194.1583047, 193.8321579, 193.506559 ,
        193.181507 , 192.857001 , 192.5330401, 192.2096235, 191.8867501,
        191.564419 , 191.2426294, 190.9213804, 190.

In [19]:
#df_base.iloc[:,0]
#row_matrix.shape
#df_matrix_1[:,0].shape
df1=np.dot(df_matrix_1,row_matrix)
#row_matrix*df_matrix_1

In [20]:
pd.DataFrame(df1)

0         1         2         3         4         5         6   \
0      0.416946  0.172489  0.172085  0.171775  0.171483  0.171194  0.170906   
1      0.416946  0.172489  0.172085  0.171775  0.171483  0.171194  0.170906   
2      0.366114  0.151460  0.151105  0.150833  0.150576  0.150323  0.150070   
3      2.511354  1.038935  1.036506  1.034638  1.032877  1.031137  1.029404   
4      0.084315  0.034881  0.034799  0.034737  0.034677  0.034619  0.034561   
...         ...       ...       ...       ...       ...       ...       ...   
11705  0.141881  0.058695  0.058558  0.058453  0.058353  0.058255  0.058157   
11706  0.425642  0.176086  0.175675  0.175358  0.175059  0.174765  0.174471   
11707  0.822208  0.340144  0.339349  0.338737  0.338160  0.337591  0.337023   
11708  0.425642  0.176086  0.175675  0.175358  0.175059  0.174765  0.174471   
11709  0.349595  0.144626  0.144288  0.144028  0.143782  0.143540  0.143299   

             7         8         9   ...        90        91        92  \
0      0.170619  0.170332  0.170046  ...  0.148397  0.148148  0.147899   
1      0.170619  0.170332  0.170046  ...  0.148397  0.148148  0.147899   
2      0.149818  0.149566  0.149315  ...  0.130305  0.130086  0.129868   
3      1.027675  1.025949  1.024225  ...  0.893828  0.892327  0.890828   
4      0.034503  0.034445  0.034387  ...  0.030009  0.029959  0.029908   
...         ...       ...       ...  ...       ...       ...       ...   
11705  0.058059  0.057962  0.057864  ...  0.050497  0.050413  0.050328   
11706  0.174178  0.173885  0.173593  ...  0.151492  0.151238  0.150984   
11707  0.336457  0.335892  0.335328  ...  0.292636  0.292145  0.291654   
11708  0.174178  0.173885  0.173593  ...  0.151492  0.151238  0.150984   
11709  0.143058  0.142818  0.142578  ...  0.124426  0.124217  0.124008   

             93        94        95        96        97        98        99  
0      0.147651  0.147403  0.147155  0.146908  0.146661  0.146415  0.146169  
1      0.147651  0.147403  0.147155  0.146908  0.146661  0.146415  0.146169  
2      0.129650  0.129432  0.129215  0.128998  0.128781  0.128565  0.128349  
3      0.889332  0.887838  0.886346  0.884857  0.883371  0.881887  0.880406  
4      0.029858  0.029808  0.029758  0.029708  0.029658  0.029608  0.029558  
...         ...       ...       ...       ...       ...       ...       ...  
11705  0.050243  0.050159  0.050075  0.049991  0.049907  0.049823  0.049739  
11706  0.150730  0.150477  0.150224  0.149972  0.149720  0.149469  0.149218  
11707  0.291164  0.290675  0.290187  0.289699  0.289213  0.288727  0.288242  
11708  0.150730  0.150477  0.150224  0.149972  0.149720  0.149469  0.149218  
11709  0.123800  0.123592  0.123384  0.123177  0.122970  0.122764  0.122557  

[11710 rows x 100 columns]

In [82]:
b=[]

In [ ]:
#循环生成数据框的名字/生成一个有99个位置的list
for i in range(0,99): #生成0-98的99个数字
  b.append("df"+str(i))
  print(b)

#Produce 99 dataframes

In [76]:
#Basic formula
#b[0]=np.dot(df_matrix_1,row_matrix)
#df_matrix_1=np.matrix(df_base.iloc[:,0]).transpose()

In [84]:
for i in range(0,99):
  b[i]=np.dot(np.matrix(df_base.iloc[:,i]).transpose(),row_matrix)

In [109]:
pd.DataFrame(b[0])

0         1         2         3         4         5         6   \
0      0.416946  0.172489  0.172085  0.171775  0.171483  0.171194  0.170906   
1      0.416946  0.172489  0.172085  0.171775  0.171483  0.171194  0.170906   
2      0.366114  0.151460  0.151105  0.150833  0.150576  0.150323  0.150070   
3      2.511354  1.038935  1.036506  1.034638  1.032877  1.031137  1.029404   
4      0.084315  0.034881  0.034799  0.034737  0.034677  0.034619  0.034561   
...         ...       ...       ...       ...       ...       ...       ...   
11705  0.141881  0.058695  0.058558  0.058453  0.058353  0.058255  0.058157   
11706  0.425642  0.176086  0.175675  0.175358  0.175059  0.174765  0.174471   
11707  0.822208  0.340144  0.339349  0.338737  0.338160  0.337591  0.337023   
11708  0.425642  0.176086  0.175675  0.175358  0.175059  0.174765  0.174471   
11709  0.349595  0.144626  0.144288  0.144028  0.143782  0.143540  0.143299   

             7         8         9   ...        90        91        92  \
0      0.170619  0.170332  0.170046  ...  0.148397  0.148148  0.147899   
1      0.170619  0.170332  0.170046  ...  0.148397  0.148148  0.147899   
2      0.149818  0.149566  0.149315  ...  0.130305  0.130086  0.129868   
3      1.027675  1.025949  1.024225  ...  0.893828  0.892327  0.890828   
4      0.034503  0.034445  0.034387  ...  0.030009  0.029959  0.029908   
...         ...       ...       ...  ...       ...       ...       ...   
11705  0.058059  0.057962  0.057864  ...  0.050497  0.050413  0.050328   
11706  0.174178  0.173885  0.173593  ...  0.151492  0.151238  0.150984   
11707  0.336457  0.335892  0.335328  ...  0.292636  0.292145  0.291654   
11708  0.174178  0.173885  0.173593  ...  0.151492  0.151238  0.150984   
11709  0.143058  0.142818  0.142578  ...  0.124426  0.124217  0.124008   

             93        94        95        96        97        98        99  
0      0.147651  0.147403  0.147155  0.146908  0.146661  0.146415  0.146169  
1      0.147651  0.147403  0.147155  0.146908  0.146661  0.146415  0.146169  
2      0.129650  0.129432  0.129215  0.128998  0.128781  0.128565  0.128349  
3      0.889332  0.887838  0.886346  0.884857  0.883371  0.881887  0.880406  
4      0.029858  0.029808  0.029758  0.029708  0.029658  0.029608  0.029558  
...         ...       ...       ...       ...       ...       ...       ...  
11705  0.050243  0.050159  0.050075  0.049991  0.049907  0.049823  0.049739  
11706  0.150730  0.150477  0.150224  0.149972  0.149720  0.149469  0.149218  
11707  0.291164  0.290675  0.290187  0.289699  0.289213  0.288727  0.288242  
11708  0.150730  0.150477  0.150224  0.149972  0.149720  0.149469  0.149218  
11709  0.123800  0.123592  0.123384  0.123177  0.122970  0.122764  0.122557  

[11710 rows x 100 columns]

In [33]:
#Choose one column of the datafram
b[0][:,0]

matrix([[0.41694597],
        [0.41694597],
        [0.36611385],
        ...,
        [0.82220846],
        [0.4256424 ],
        [0.34959472]])

#Sum

In [ ]:
#Basic formula
b[0][:,1]+b[1][:,0]

In [107]:
b[0][:,0]

matrix([[0.41694597],
        [0.41694597],
        [0.36611385],
        ...,
        [0.82220846],
        [0.4256424 ],
        [0.34959472]])

In [ ]:
df_none=pd.DataFrame()
df_none.loc[:,0]=pd.DataFrame(b[0][:,0])
df_none

In [97]:
#Test
df_none.loc[:,0]=pd.DataFrame(b[0][:,1])
df_none.loc[:,1]=pd.DataFrame(b[1][:,0])
df_none

0          1
0      0.172489   2.390960
1      0.172489   2.390960
2      0.151460   3.378174
3      1.038935  15.060931
4      0.034881   0.815215
...         ...        ...
11705  0.058695   1.018317
11706  0.176086   3.054951
11707  0.340144   7.356527
11708  0.176086   3.054951
11709  0.144626   2.810005

[11710 rows x 2 columns]

In [105]:
pd.DataFrame(b[0])

0         1         2         3         4         5         6   \
0      0.416946  0.172489  0.172085  0.171775  0.171483  0.171194  0.170906   
1      0.416946  0.172489  0.172085  0.171775  0.171483  0.171194  0.170906   
2      0.366114  0.151460  0.151105  0.150833  0.150576  0.150323  0.150070   
3      2.511354  1.038935  1.036506  1.034638  1.032877  1.031137  1.029404   
4      0.084315  0.034881  0.034799  0.034737  0.034677  0.034619  0.034561   
...         ...       ...       ...       ...       ...       ...       ...   
11705  0.141881  0.058695  0.058558  0.058453  0.058353  0.058255  0.058157   
11706  0.425642  0.176086  0.175675  0.175358  0.175059  0.174765  0.174471   
11707  0.822208  0.340144  0.339349  0.338737  0.338160  0.337591  0.337023   
11708  0.425642  0.176086  0.175675  0.175358  0.175059  0.174765  0.174471   
11709  0.349595  0.144626  0.144288  0.144028  0.143782  0.143540  0.143299   

             7         8         9   ...        90        91        92  \
0      0.170619  0.170332  0.170046  ...  0.148397  0.148148  0.147899   
1      0.170619  0.170332  0.170046  ...  0.148397  0.148148  0.147899   
2      0.149818  0.149566  0.149315  ...  0.130305  0.130086  0.129868   
3      1.027675  1.025949  1.024225  ...  0.893828  0.892327  0.890828   
4      0.034503  0.034445  0.034387  ...  0.030009  0.029959  0.029908   
...         ...       ...       ...  ...       ...       ...       ...   
11705  0.058059  0.057962  0.057864  ...  0.050497  0.050413  0.050328   
11706  0.174178  0.173885  0.173593  ...  0.151492  0.151238  0.150984   
11707  0.336457  0.335892  0.335328  ...  0.292636  0.292145  0.291654   
11708  0.174178  0.173885  0.173593  ...  0.151492  0.151238  0.150984   
11709  0.143058  0.142818  0.142578  ...  0.124426  0.124217  0.124008   

             93        94        95        96        97        98        99  
0      0.147651  0.147403  0.147155  0.146908  0.146661  0.146415  0.146169  
1      0.147651  0.147403  0.147155  0.146908  0.146661  0.146415  0.146169  
2      0.129650  0.129432  0.129215  0.128998  0.128781  0.128565  0.128349  
3      0.889332  0.887838  0.886346  0.884857  0.883371  0.881887  0.880406  
4      0.029858  0.029808  0.029758  0.029708  0.029658  0.029608  0.029558  
...         ...       ...       ...       ...       ...       ...       ...  
11705  0.050243  0.050159  0.050075  0.049991  0.049907  0.049823  0.049739  
11706  0.150730  0.150477  0.150224  0.149972  0.149720  0.149469  0.149218  
11707  0.291164  0.290675  0.290187  0.289699  0.289213  0.288727  0.288242  
11708  0.150730  0.150477  0.150224  0.149972  0.149720  0.149469  0.149218  
11709  0.123800  0.123592  0.123384  0.123177  0.122970  0.122764  0.122557  

[11710 rows x 100 columns]

In [98]:
df_none.sum(axis=1)

0         2.563449
1         2.563449
2         3.529633
3        16.099866
4         0.850095
           ...    
11705     1.077012
11706     3.231038
11707     7.696671
11708     3.231038
11709     2.954631
Length: 11710, dtype: float64

In [80]:
b[0][:,99]

matrix([[0.14616879],
        [0.14616879],
        [0.12834857],
        ...,
        [0.28824171],
        [0.1492175 ],
        [0.12255746]])

In [ ]:
summ=[]
for i in range(0,99):
  summ.append("col"+str(i))
  print(summ)

In [ ]:
for j in range(0,99): #0到98,99个数
    df_none=pd.DataFrame()
    for i in range(0,j+1): #0,...,98
        df_none.loc[:,i]=pd.DataFrame(b[i][:,j-i])
        #print(df_none)
    summ[i]=df_none.sum(axis=1) #axis=0行，axis=1列相加
    print(df_none)

In [110]:
summ

[0        0.416946
 1        0.416946
 2        0.366114
 3        2.511354
 4        0.084315
            ...   
 11705    0.141881
 11706    0.425642
 11707    0.822208
 11708    0.425642
 11709    0.349595
 Length: 11710, dtype: float64, 0         2.563449
 1         2.563449
 2         3.529633
 3        16.099866
 4         0.850095
            ...    
 11705     1.077012
 11706     3.231038
 11707     7.696671
 11708     3.231038
 11709     2.954631
 Length: 11710, dtype: float64, 0        12.730479
 1        12.730479
 2         6.331550
 3        79.667055
 4         1.520708
            ...    
 11705     5.238498
 11706    15.715493
 11707    17.947672
 11708    15.715493
 11709    14.184703
 Length: 11710, dtype: float64, 0         40.249901
 1         40.249901
 2         24.329293
 3        251.308173
 4          5.806775
             ...    
 11705     16.353338
 11706     49.060013
 11707     69.222390
 11708     49.060013
 11709     24.535991
 Length: 11710, dtype: floa

In [111]:
result=pd.DataFrame(summ).transpose()

In [112]:
result

0          1          2           3           4            5   \
0      0.416946   2.563449  12.730479   40.249901   99.015010   207.320059   
1      0.416946   2.563449  12.730479   40.249901   99.015010   207.320059   
2      0.366114   3.529633   6.331550   24.329293   69.137568   159.636944   
3      2.511354  16.099866  79.667055  251.308173  617.501625  1292.258630   
4      0.084315   0.850095   1.520708    5.806775   16.448678    37.919793   
...         ...        ...        ...         ...         ...          ...   
11705  0.141881   1.077012   5.238498   16.353338   39.966899    61.797936   
11706  0.425642   3.231038  15.715493   49.060013  119.900698   185.393808   
11707  0.822208   7.696671  17.947672   69.222390  111.186200   266.213892   
11708  0.425642   3.231038  15.715493   49.060013  119.900698   185.393808   
11709  0.349595   2.954631  14.184703   24.535991   63.492007   142.392653   

                6            7            8            9   ...             89  \
0       306.916032   518.842534   706.059565   915.290462  ...   28707.235796   
1       306.916032   518.842534   706.059565   915.290462  ...   28707.235796   
2       238.916741   427.956323   589.389808   770.638432  ...   27279.109615   
3      1912.538510  3233.165080  4399.976336  5704.546563  ...  174240.856127   
4        56.711235   101.536730   139.807202   182.785925  ...    6285.031400   
...            ...          ...          ...          ...  ...            ...   
11705   114.351842   160.745432   258.660693   342.920984  ...   10318.335044   
11706   343.055527   482.236297   775.982079  1028.762953  ...   30955.005132   
11707   392.477909   746.916324  1034.833746  1713.048861  ...   58069.698019   
11708   343.055527   482.236297   775.982079  1028.762953  ...   30955.005132   
11709   211.673782   376.677945   517.635201   812.927307  ...   25816.636129   

                  90             91             92             93  \
0       29212.601172   29737.844141   30628.640762   31339.437632   
1       29212.601172   29737.844141   30628.640762   31339.437632   
2       27782.729279   28311.051698   28861.424161   29848.906314   
3      177414.886989  180716.160136  184125.266756  189880.842647   
4        6405.311708    6531.565459    6663.186200    6799.542440   
...              ...            ...            ...            ...   
11705   10592.912639   10812.273077   11039.485146   11273.364036   
11706   31778.737915   32436.819231   33118.455435   33820.092105   
11707   59116.896165   60222.689186   61382.446926   63624.771450   
11708   31778.737915   32436.819231   33118.455435   33820.092105   
11709   26246.645047   27026.285486   27645.048305   28283.180249   

                  94             95             96             97  \
0       32063.233704   32796.531894   33535.977272   34710.285477   
1       32063.233704   32796.531894   33535.977272   34710.285477   
2       30622.332429   31413.367965   32218.728571   33035.177294   
3      194441.112331  199064.528089  203730.466618  208419.268018   
4        7043.224353    7232.902565    7426.163485    7622.257361   
...              ...            ...            ...            ...   
11705   11512.726013   11914.177828   12229.299833   12547.004446   
11706   34538.178036   35742.533481   36687.899497   37641.013338   
11707   65347.288739   67121.249980   68940.042228   70796.953020   
11708   34538.178036   35742.533481   36687.899497   37641.013338   
11709   28937.623370   29605.333976   30283.362370   31414.630691   

                  98  
0       35633.914770  
1       35633.914770  
2       33859.610105  
3      215849.984669  
4        7820.448834  
...              ...  
11705   12866.099310  
11706   38598.297927  
11707   72685.380751  
11708   38598.297927  
11709   32294.775682  

[11710 rows x 99 columns]

In [114]:
result.to_csv("/content/result.csv")